[PULL REQUEST] SQL Database Build #57
SANDAG/Cohort-Component-Model pull request #65
Opened 2024-11-06 17:34 UTC by nmad-sandag

**Describe this pull request. What changes are being made?**
The Cohort Component model currently only outputs csv files for each run to an [output folder]. The results from each run is saved in SQL database for tracking, or reporting across hundreds of model runs nor for scenario/run tracking

**What issues does this pull request address?**
#57 closed

2024-11-06 18:21 UTC, GregorSchroeder requested changes

2024-11-06 18:21 UTC, GregorSchroeder commented on sql/db_build/table_creation.sql
- use brackets `[ ]` for all column names, table names, schema names
- suggest renaming `[metadata].[ccm_run]` to just `[metadata].[run]`
- suggest renaming output tables to match their default output csv file names
  - [outputs].[components]
  - [outputs].[population]
  - [outputs].[rates]
- add foreign key constraints in all tables back to the `[metadata].[run]` table
- remove `[inputs]` schema creation as it is not used
- add `CLUSTERED COLUMNSTORE INDEX`s to all `[output]` tables and `UNIQUE` constraints on their unique composite keys

2024-11-06 18:21 UTC, GregorSchroeder commented on python/etl.py
- remove all ETL related things as no issue has been created
- this looks overly complex for what should be a generic read of csv files and insert into sql tables verbatim for almost everything

2024-11-06 23:21 UTC, nmad-sandag commented on python/etl.py
I will work on making it less complex :)

2024-11-08 15:47 UTC, GregorSchroeder approved these changes
Looks good! Please make a new issue describing the new ETL feature wanted and then begin work on that.

2024-11-08 17:34 UTC, merged